spring:
  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${FRIZER_DB_PORT:5432}/frizer
    username: frizer
    password: ${FRIZER_DB_PASSWORD}
  thymeleaf:
    cache: false

logging:
  level:
    com.euiseon.friger.inventory.dao: DEBUG
    com.euiseon.friger.history.dao: DEBUG
