spring:
  datasource:
    url: ${FRIZER_DB_URL}
    username: ${FRIZER_DB_USERNAME}
    password: ${FRIZER_DB_PASSWORD}
  thymeleaf:
    cache: true

logging:
  level:
    root: INFO
    org.apache.ibatis: WARN
    com.euiseon.friger: INFO

server:
  error:
    include-message: never
    include-stacktrace: never
