CREATE TABLE food_item (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , food_name VARCHAR(100) NOT NULL
  , storage_type VARCHAR(20) NOT NULL
  , category VARCHAR(50)
  , quantity_text VARCHAR(50)
  , expired_at DATE
  , purchased_at DATE
  , opened_at DATE
  , frozen_at DATE
  , source_type VARCHAR(30) NOT NULL DEFAULT 'ETC'
  , freeze_type VARCHAR(30) NOT NULL DEFAULT 'NONE'
  , status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
  , memo VARCHAR(500)
  , created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT ck_food_item_name_not_blank CHECK (btrim(food_name) <> '')
  , CONSTRAINT ck_food_item_storage CHECK (storage_type IN ('FRIDGE', 'FREEZER', 'ROOM'))
  , CONSTRAINT ck_food_item_source CHECK (
        source_type IN ('PURCHASE', 'DELIVERY', 'DELIVERY_LEFTOVER', 'COOKED', 'ETC')
    )
  , CONSTRAINT ck_food_item_freeze_type CHECK (
        freeze_type IN ('NONE', 'HOME_FROZEN', 'COMMERCIAL_FROZEN')
    )
  , CONSTRAINT ck_food_item_status CHECK (status IN ('ACTIVE', 'CONSUMED', 'DISCARDED'))
  , CONSTRAINT ck_food_item_storage_freeze CHECK (
        (storage_type = 'FREEZER' AND freeze_type IN ('HOME_FROZEN', 'COMMERCIAL_FROZEN'))
        OR
        (storage_type IN ('FRIDGE', 'ROOM') AND freeze_type = 'NONE' AND frozen_at IS NULL)
    )
);

COMMENT ON COLUMN food_item.frozen_at IS
    'Home freezer storage start date; NULL means unknown for FREEZER, inapplicable otherwise.';

CREATE TABLE food_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  , food_id BIGINT NOT NULL
  , action_type VARCHAR(20) NOT NULL
  , previous_storage_type VARCHAR(20)
  , new_storage_type VARCHAR(20) NOT NULL
  , quantity_text VARCHAR(50)
  , memo VARCHAR(500)
  , created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  , CONSTRAINT fk_food_history_food FOREIGN KEY (food_id)
        REFERENCES food_item (food_id) ON DELETE RESTRICT
  , CONSTRAINT ck_food_history_action CHECK (
        action_type IN ('CREATE', 'CONSUME', 'FREEZE', 'MOVE', 'DISCARD')
    )
  , CONSTRAINT ck_food_history_previous_storage CHECK (
        previous_storage_type IN ('FRIDGE', 'FREEZER', 'ROOM')
    )
  , CONSTRAINT ck_food_history_new_storage CHECK (
        new_storage_type IN ('FRIDGE', 'FREEZER', 'ROOM')
    )
  , CONSTRAINT ck_food_history_transition CHECK (
        (action_type = 'CREATE' AND previous_storage_type IS NULL)
        OR
        (action_type IN ('CONSUME', 'DISCARD')
            AND previous_storage_type IS NOT NULL
            AND previous_storage_type = new_storage_type)
        OR
        (action_type = 'FREEZE'
            AND previous_storage_type IS NOT NULL
            AND previous_storage_type IN ('FRIDGE', 'ROOM')
            AND new_storage_type = 'FREEZER')
        OR
        (action_type = 'MOVE'
            AND previous_storage_type IS NOT NULL
            AND previous_storage_type <> new_storage_type
            AND new_storage_type IN ('FRIDGE', 'ROOM'))
    )
);

CREATE INDEX ix_food_item_active_expired
    ON food_item (expired_at)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_food_item_active_frozen
    ON food_item (frozen_at)
    WHERE status = 'ACTIVE'
      AND storage_type = 'FREEZER';

CREATE INDEX ix_food_history_created
    ON food_history (created_at DESC);
