CREATE TABLE food_master (
    master_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name VARCHAR(100) NOT NULL CHECK (btrim(food_name) <> ''),
    category VARCHAR(50),
    default_quantity_unit VARCHAR(10),
    default_exclude_expiry_warning BOOLEAN NOT NULL DEFAULT FALSE,
    default_exclude_opened_warning BOOLEAN NOT NULL DEFAULT FALSE,
    version_no BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One master per existing item, including identically named items. Never infer identity from names.
INSERT INTO food_master(master_id, food_name, category, default_quantity_unit, created_at, updated_at)
SELECT food_id, food_name, category, quantity_unit, created_at, updated_at FROM food_item;
SELECT setval(pg_get_serial_sequence('food_master', 'master_id'),
    COALESCE((SELECT max(master_id) FROM food_master), 1), EXISTS(SELECT 1 FROM food_master));
ALTER TABLE food_item ADD COLUMN master_id BIGINT;
UPDATE food_item SET master_id = food_id;
ALTER TABLE food_item ALTER COLUMN master_id SET NOT NULL;
ALTER TABLE food_item ADD CONSTRAINT fk_food_item_master FOREIGN KEY(master_id)
    REFERENCES food_master(master_id) ON DELETE RESTRICT;
ALTER TABLE food_history ADD COLUMN recorded_food_name VARCHAR(100);
UPDATE food_history h SET recorded_food_name = CASE
    WHEN h.changes_text LIKE 'snapshot-v1:%' THEN COALESCE(substring(h.changes_text FROM 13)::jsonb ->> '음식명', i.food_name)
    ELSE i.food_name END
FROM food_item i WHERE i.food_id=h.food_id;
ALTER TABLE food_item DROP COLUMN food_name, DROP COLUMN category;
CREATE INDEX ix_food_item_master ON food_item(master_id);

-- Immutable merge receipt: source identifiers intentionally outlive the deleted master.
CREATE TABLE food_merge_receipt (
    request_id UUID PRIMARY KEY,
    source_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    source_version BIGINT NOT NULL,
    target_version BIGINT NOT NULL,
    source_name VARCHAR(100) NOT NULL,
    target_name VARCHAR(100) NOT NULL,
    item_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(source_id <> target_id)
);
